/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package xdrSchema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class XdrHttpInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4913297418508268213L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"XdrHttpInfo\",\"namespace\":\"xdrSchema\",\"fields\":[{\"name\":\"CtionTime\",\"type\":\"long\",\"default\":0},{\"name\":\"FirstPacketTime\",\"type\":\"long\",\"default\":0},{\"name\":\"LastPacketTime\",\"type\":\"long\",\"default\":0},{\"name\":\"ServiceTime\",\"type\":\"long\",\"default\":0},{\"name\":\"ContentLenth\",\"type\":\"long\",\"default\":0},{\"name\":\"HttpStatus\",\"type\":\"int\",\"default\":0},{\"name\":\"HttpMethod\",\"type\":\"int\",\"default\":0},{\"name\":\"HttpVersion\",\"type\":\"int\",\"default\":0},{\"name\":\"FirstRequestFlag\",\"type\":\"int\",\"default\":0},{\"name\":\"SerFlag\",\"type\":\"int\",\"default\":0},{\"name\":\"HeadFlag\",\"type\":\"int\",\"default\":0},{\"name\":\"Res\",\"type\":\"int\",\"default\":0},{\"name\":\"Ie\",\"type\":\"int\",\"default\":0},{\"name\":\"Portal\",\"type\":\"int\",\"default\":0},{\"name\":\"Resv\",\"type\":\"int\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<XdrHttpInfo> ENCODER =
      new BinaryMessageEncoder<XdrHttpInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<XdrHttpInfo> DECODER =
      new BinaryMessageDecoder<XdrHttpInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<XdrHttpInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<XdrHttpInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<XdrHttpInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this XdrHttpInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a XdrHttpInfo from a ByteBuffer. */
  public static XdrHttpInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long CtionTime;
  @Deprecated public long FirstPacketTime;
  @Deprecated public long LastPacketTime;
  @Deprecated public long ServiceTime;
  @Deprecated public long ContentLenth;
  @Deprecated public int HttpStatus;
  @Deprecated public int HttpMethod;
  @Deprecated public int HttpVersion;
  @Deprecated public int FirstRequestFlag;
  @Deprecated public int SerFlag;
  @Deprecated public int HeadFlag;
  @Deprecated public int Res;
  @Deprecated public int Ie;
  @Deprecated public int Portal;
  @Deprecated public int Resv;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public XdrHttpInfo() {}

  /**
   * All-args constructor.
   * @param CtionTime The new value for CtionTime
   * @param FirstPacketTime The new value for FirstPacketTime
   * @param LastPacketTime The new value for LastPacketTime
   * @param ServiceTime The new value for ServiceTime
   * @param ContentLenth The new value for ContentLenth
   * @param HttpStatus The new value for HttpStatus
   * @param HttpMethod The new value for HttpMethod
   * @param HttpVersion The new value for HttpVersion
   * @param FirstRequestFlag The new value for FirstRequestFlag
   * @param SerFlag The new value for SerFlag
   * @param HeadFlag The new value for HeadFlag
   * @param Res The new value for Res
   * @param Ie The new value for Ie
   * @param Portal The new value for Portal
   * @param Resv The new value for Resv
   */
  public XdrHttpInfo(java.lang.Long CtionTime, java.lang.Long FirstPacketTime, java.lang.Long LastPacketTime, java.lang.Long ServiceTime, java.lang.Long ContentLenth, java.lang.Integer HttpStatus, java.lang.Integer HttpMethod, java.lang.Integer HttpVersion, java.lang.Integer FirstRequestFlag, java.lang.Integer SerFlag, java.lang.Integer HeadFlag, java.lang.Integer Res, java.lang.Integer Ie, java.lang.Integer Portal, java.lang.Integer Resv) {
    this.CtionTime = CtionTime;
    this.FirstPacketTime = FirstPacketTime;
    this.LastPacketTime = LastPacketTime;
    this.ServiceTime = ServiceTime;
    this.ContentLenth = ContentLenth;
    this.HttpStatus = HttpStatus;
    this.HttpMethod = HttpMethod;
    this.HttpVersion = HttpVersion;
    this.FirstRequestFlag = FirstRequestFlag;
    this.SerFlag = SerFlag;
    this.HeadFlag = HeadFlag;
    this.Res = Res;
    this.Ie = Ie;
    this.Portal = Portal;
    this.Resv = Resv;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CtionTime;
    case 1: return FirstPacketTime;
    case 2: return LastPacketTime;
    case 3: return ServiceTime;
    case 4: return ContentLenth;
    case 5: return HttpStatus;
    case 6: return HttpMethod;
    case 7: return HttpVersion;
    case 8: return FirstRequestFlag;
    case 9: return SerFlag;
    case 10: return HeadFlag;
    case 11: return Res;
    case 12: return Ie;
    case 13: return Portal;
    case 14: return Resv;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CtionTime = (java.lang.Long)value$; break;
    case 1: FirstPacketTime = (java.lang.Long)value$; break;
    case 2: LastPacketTime = (java.lang.Long)value$; break;
    case 3: ServiceTime = (java.lang.Long)value$; break;
    case 4: ContentLenth = (java.lang.Long)value$; break;
    case 5: HttpStatus = (java.lang.Integer)value$; break;
    case 6: HttpMethod = (java.lang.Integer)value$; break;
    case 7: HttpVersion = (java.lang.Integer)value$; break;
    case 8: FirstRequestFlag = (java.lang.Integer)value$; break;
    case 9: SerFlag = (java.lang.Integer)value$; break;
    case 10: HeadFlag = (java.lang.Integer)value$; break;
    case 11: Res = (java.lang.Integer)value$; break;
    case 12: Ie = (java.lang.Integer)value$; break;
    case 13: Portal = (java.lang.Integer)value$; break;
    case 14: Resv = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CtionTime' field.
   * @return The value of the 'CtionTime' field.
   */
  public java.lang.Long getCtionTime() {
    return CtionTime;
  }

  /**
   * Sets the value of the 'CtionTime' field.
   * @param value the value to set.
   */
  public void setCtionTime(java.lang.Long value) {
    this.CtionTime = value;
  }

  /**
   * Gets the value of the 'FirstPacketTime' field.
   * @return The value of the 'FirstPacketTime' field.
   */
  public java.lang.Long getFirstPacketTime() {
    return FirstPacketTime;
  }

  /**
   * Sets the value of the 'FirstPacketTime' field.
   * @param value the value to set.
   */
  public void setFirstPacketTime(java.lang.Long value) {
    this.FirstPacketTime = value;
  }

  /**
   * Gets the value of the 'LastPacketTime' field.
   * @return The value of the 'LastPacketTime' field.
   */
  public java.lang.Long getLastPacketTime() {
    return LastPacketTime;
  }

  /**
   * Sets the value of the 'LastPacketTime' field.
   * @param value the value to set.
   */
  public void setLastPacketTime(java.lang.Long value) {
    this.LastPacketTime = value;
  }

  /**
   * Gets the value of the 'ServiceTime' field.
   * @return The value of the 'ServiceTime' field.
   */
  public java.lang.Long getServiceTime() {
    return ServiceTime;
  }

  /**
   * Sets the value of the 'ServiceTime' field.
   * @param value the value to set.
   */
  public void setServiceTime(java.lang.Long value) {
    this.ServiceTime = value;
  }

  /**
   * Gets the value of the 'ContentLenth' field.
   * @return The value of the 'ContentLenth' field.
   */
  public java.lang.Long getContentLenth() {
    return ContentLenth;
  }

  /**
   * Sets the value of the 'ContentLenth' field.
   * @param value the value to set.
   */
  public void setContentLenth(java.lang.Long value) {
    this.ContentLenth = value;
  }

  /**
   * Gets the value of the 'HttpStatus' field.
   * @return The value of the 'HttpStatus' field.
   */
  public java.lang.Integer getHttpStatus() {
    return HttpStatus;
  }

  /**
   * Sets the value of the 'HttpStatus' field.
   * @param value the value to set.
   */
  public void setHttpStatus(java.lang.Integer value) {
    this.HttpStatus = value;
  }

  /**
   * Gets the value of the 'HttpMethod' field.
   * @return The value of the 'HttpMethod' field.
   */
  public java.lang.Integer getHttpMethod() {
    return HttpMethod;
  }

  /**
   * Sets the value of the 'HttpMethod' field.
   * @param value the value to set.
   */
  public void setHttpMethod(java.lang.Integer value) {
    this.HttpMethod = value;
  }

  /**
   * Gets the value of the 'HttpVersion' field.
   * @return The value of the 'HttpVersion' field.
   */
  public java.lang.Integer getHttpVersion() {
    return HttpVersion;
  }

  /**
   * Sets the value of the 'HttpVersion' field.
   * @param value the value to set.
   */
  public void setHttpVersion(java.lang.Integer value) {
    this.HttpVersion = value;
  }

  /**
   * Gets the value of the 'FirstRequestFlag' field.
   * @return The value of the 'FirstRequestFlag' field.
   */
  public java.lang.Integer getFirstRequestFlag() {
    return FirstRequestFlag;
  }

  /**
   * Sets the value of the 'FirstRequestFlag' field.
   * @param value the value to set.
   */
  public void setFirstRequestFlag(java.lang.Integer value) {
    this.FirstRequestFlag = value;
  }

  /**
   * Gets the value of the 'SerFlag' field.
   * @return The value of the 'SerFlag' field.
   */
  public java.lang.Integer getSerFlag() {
    return SerFlag;
  }

  /**
   * Sets the value of the 'SerFlag' field.
   * @param value the value to set.
   */
  public void setSerFlag(java.lang.Integer value) {
    this.SerFlag = value;
  }

  /**
   * Gets the value of the 'HeadFlag' field.
   * @return The value of the 'HeadFlag' field.
   */
  public java.lang.Integer getHeadFlag() {
    return HeadFlag;
  }

  /**
   * Sets the value of the 'HeadFlag' field.
   * @param value the value to set.
   */
  public void setHeadFlag(java.lang.Integer value) {
    this.HeadFlag = value;
  }

  /**
   * Gets the value of the 'Res' field.
   * @return The value of the 'Res' field.
   */
  public java.lang.Integer getRes() {
    return Res;
  }

  /**
   * Sets the value of the 'Res' field.
   * @param value the value to set.
   */
  public void setRes(java.lang.Integer value) {
    this.Res = value;
  }

  /**
   * Gets the value of the 'Ie' field.
   * @return The value of the 'Ie' field.
   */
  public java.lang.Integer getIe() {
    return Ie;
  }

  /**
   * Sets the value of the 'Ie' field.
   * @param value the value to set.
   */
  public void setIe(java.lang.Integer value) {
    this.Ie = value;
  }

  /**
   * Gets the value of the 'Portal' field.
   * @return The value of the 'Portal' field.
   */
  public java.lang.Integer getPortal() {
    return Portal;
  }

  /**
   * Sets the value of the 'Portal' field.
   * @param value the value to set.
   */
  public void setPortal(java.lang.Integer value) {
    this.Portal = value;
  }

  /**
   * Gets the value of the 'Resv' field.
   * @return The value of the 'Resv' field.
   */
  public java.lang.Integer getResv() {
    return Resv;
  }

  /**
   * Sets the value of the 'Resv' field.
   * @param value the value to set.
   */
  public void setResv(java.lang.Integer value) {
    this.Resv = value;
  }

  /**
   * Creates a new XdrHttpInfo RecordBuilder.
   * @return A new XdrHttpInfo RecordBuilder
   */
  public static xdrSchema.XdrHttpInfo.Builder newBuilder() {
    return new xdrSchema.XdrHttpInfo.Builder();
  }

  /**
   * Creates a new XdrHttpInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new XdrHttpInfo RecordBuilder
   */
  public static xdrSchema.XdrHttpInfo.Builder newBuilder(xdrSchema.XdrHttpInfo.Builder other) {
    return new xdrSchema.XdrHttpInfo.Builder(other);
  }

  /**
   * Creates a new XdrHttpInfo RecordBuilder by copying an existing XdrHttpInfo instance.
   * @param other The existing instance to copy.
   * @return A new XdrHttpInfo RecordBuilder
   */
  public static xdrSchema.XdrHttpInfo.Builder newBuilder(xdrSchema.XdrHttpInfo other) {
    return new xdrSchema.XdrHttpInfo.Builder(other);
  }

  /**
   * RecordBuilder for XdrHttpInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<XdrHttpInfo>
    implements org.apache.avro.data.RecordBuilder<XdrHttpInfo> {

    private long CtionTime;
    private long FirstPacketTime;
    private long LastPacketTime;
    private long ServiceTime;
    private long ContentLenth;
    private int HttpStatus;
    private int HttpMethod;
    private int HttpVersion;
    private int FirstRequestFlag;
    private int SerFlag;
    private int HeadFlag;
    private int Res;
    private int Ie;
    private int Portal;
    private int Resv;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(xdrSchema.XdrHttpInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CtionTime)) {
        this.CtionTime = data().deepCopy(fields()[0].schema(), other.CtionTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.FirstPacketTime)) {
        this.FirstPacketTime = data().deepCopy(fields()[1].schema(), other.FirstPacketTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.LastPacketTime)) {
        this.LastPacketTime = data().deepCopy(fields()[2].schema(), other.LastPacketTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ServiceTime)) {
        this.ServiceTime = data().deepCopy(fields()[3].schema(), other.ServiceTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ContentLenth)) {
        this.ContentLenth = data().deepCopy(fields()[4].schema(), other.ContentLenth);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.HttpStatus)) {
        this.HttpStatus = data().deepCopy(fields()[5].schema(), other.HttpStatus);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.HttpMethod)) {
        this.HttpMethod = data().deepCopy(fields()[6].schema(), other.HttpMethod);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.HttpVersion)) {
        this.HttpVersion = data().deepCopy(fields()[7].schema(), other.HttpVersion);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.FirstRequestFlag)) {
        this.FirstRequestFlag = data().deepCopy(fields()[8].schema(), other.FirstRequestFlag);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.SerFlag)) {
        this.SerFlag = data().deepCopy(fields()[9].schema(), other.SerFlag);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.HeadFlag)) {
        this.HeadFlag = data().deepCopy(fields()[10].schema(), other.HeadFlag);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.Res)) {
        this.Res = data().deepCopy(fields()[11].schema(), other.Res);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.Ie)) {
        this.Ie = data().deepCopy(fields()[12].schema(), other.Ie);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.Portal)) {
        this.Portal = data().deepCopy(fields()[13].schema(), other.Portal);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.Resv)) {
        this.Resv = data().deepCopy(fields()[14].schema(), other.Resv);
        fieldSetFlags()[14] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing XdrHttpInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(xdrSchema.XdrHttpInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CtionTime)) {
        this.CtionTime = data().deepCopy(fields()[0].schema(), other.CtionTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.FirstPacketTime)) {
        this.FirstPacketTime = data().deepCopy(fields()[1].schema(), other.FirstPacketTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.LastPacketTime)) {
        this.LastPacketTime = data().deepCopy(fields()[2].schema(), other.LastPacketTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ServiceTime)) {
        this.ServiceTime = data().deepCopy(fields()[3].schema(), other.ServiceTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ContentLenth)) {
        this.ContentLenth = data().deepCopy(fields()[4].schema(), other.ContentLenth);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.HttpStatus)) {
        this.HttpStatus = data().deepCopy(fields()[5].schema(), other.HttpStatus);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.HttpMethod)) {
        this.HttpMethod = data().deepCopy(fields()[6].schema(), other.HttpMethod);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.HttpVersion)) {
        this.HttpVersion = data().deepCopy(fields()[7].schema(), other.HttpVersion);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.FirstRequestFlag)) {
        this.FirstRequestFlag = data().deepCopy(fields()[8].schema(), other.FirstRequestFlag);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.SerFlag)) {
        this.SerFlag = data().deepCopy(fields()[9].schema(), other.SerFlag);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.HeadFlag)) {
        this.HeadFlag = data().deepCopy(fields()[10].schema(), other.HeadFlag);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.Res)) {
        this.Res = data().deepCopy(fields()[11].schema(), other.Res);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.Ie)) {
        this.Ie = data().deepCopy(fields()[12].schema(), other.Ie);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.Portal)) {
        this.Portal = data().deepCopy(fields()[13].schema(), other.Portal);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.Resv)) {
        this.Resv = data().deepCopy(fields()[14].schema(), other.Resv);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'CtionTime' field.
      * @return The value.
      */
    public java.lang.Long getCtionTime() {
      return CtionTime;
    }

    /**
      * Sets the value of the 'CtionTime' field.
      * @param value The value of 'CtionTime'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setCtionTime(long value) {
      validate(fields()[0], value);
      this.CtionTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CtionTime' field has been set.
      * @return True if the 'CtionTime' field has been set, false otherwise.
      */
    public boolean hasCtionTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CtionTime' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearCtionTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'FirstPacketTime' field.
      * @return The value.
      */
    public java.lang.Long getFirstPacketTime() {
      return FirstPacketTime;
    }

    /**
      * Sets the value of the 'FirstPacketTime' field.
      * @param value The value of 'FirstPacketTime'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setFirstPacketTime(long value) {
      validate(fields()[1], value);
      this.FirstPacketTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'FirstPacketTime' field has been set.
      * @return True if the 'FirstPacketTime' field has been set, false otherwise.
      */
    public boolean hasFirstPacketTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'FirstPacketTime' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearFirstPacketTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'LastPacketTime' field.
      * @return The value.
      */
    public java.lang.Long getLastPacketTime() {
      return LastPacketTime;
    }

    /**
      * Sets the value of the 'LastPacketTime' field.
      * @param value The value of 'LastPacketTime'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setLastPacketTime(long value) {
      validate(fields()[2], value);
      this.LastPacketTime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'LastPacketTime' field has been set.
      * @return True if the 'LastPacketTime' field has been set, false otherwise.
      */
    public boolean hasLastPacketTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'LastPacketTime' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearLastPacketTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ServiceTime' field.
      * @return The value.
      */
    public java.lang.Long getServiceTime() {
      return ServiceTime;
    }

    /**
      * Sets the value of the 'ServiceTime' field.
      * @param value The value of 'ServiceTime'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setServiceTime(long value) {
      validate(fields()[3], value);
      this.ServiceTime = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ServiceTime' field has been set.
      * @return True if the 'ServiceTime' field has been set, false otherwise.
      */
    public boolean hasServiceTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ServiceTime' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearServiceTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ContentLenth' field.
      * @return The value.
      */
    public java.lang.Long getContentLenth() {
      return ContentLenth;
    }

    /**
      * Sets the value of the 'ContentLenth' field.
      * @param value The value of 'ContentLenth'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setContentLenth(long value) {
      validate(fields()[4], value);
      this.ContentLenth = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ContentLenth' field has been set.
      * @return True if the 'ContentLenth' field has been set, false otherwise.
      */
    public boolean hasContentLenth() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ContentLenth' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearContentLenth() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'HttpStatus' field.
      * @return The value.
      */
    public java.lang.Integer getHttpStatus() {
      return HttpStatus;
    }

    /**
      * Sets the value of the 'HttpStatus' field.
      * @param value The value of 'HttpStatus'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setHttpStatus(int value) {
      validate(fields()[5], value);
      this.HttpStatus = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'HttpStatus' field has been set.
      * @return True if the 'HttpStatus' field has been set, false otherwise.
      */
    public boolean hasHttpStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'HttpStatus' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearHttpStatus() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'HttpMethod' field.
      * @return The value.
      */
    public java.lang.Integer getHttpMethod() {
      return HttpMethod;
    }

    /**
      * Sets the value of the 'HttpMethod' field.
      * @param value The value of 'HttpMethod'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setHttpMethod(int value) {
      validate(fields()[6], value);
      this.HttpMethod = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'HttpMethod' field has been set.
      * @return True if the 'HttpMethod' field has been set, false otherwise.
      */
    public boolean hasHttpMethod() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'HttpMethod' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearHttpMethod() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'HttpVersion' field.
      * @return The value.
      */
    public java.lang.Integer getHttpVersion() {
      return HttpVersion;
    }

    /**
      * Sets the value of the 'HttpVersion' field.
      * @param value The value of 'HttpVersion'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setHttpVersion(int value) {
      validate(fields()[7], value);
      this.HttpVersion = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'HttpVersion' field has been set.
      * @return True if the 'HttpVersion' field has been set, false otherwise.
      */
    public boolean hasHttpVersion() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'HttpVersion' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearHttpVersion() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'FirstRequestFlag' field.
      * @return The value.
      */
    public java.lang.Integer getFirstRequestFlag() {
      return FirstRequestFlag;
    }

    /**
      * Sets the value of the 'FirstRequestFlag' field.
      * @param value The value of 'FirstRequestFlag'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setFirstRequestFlag(int value) {
      validate(fields()[8], value);
      this.FirstRequestFlag = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'FirstRequestFlag' field has been set.
      * @return True if the 'FirstRequestFlag' field has been set, false otherwise.
      */
    public boolean hasFirstRequestFlag() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'FirstRequestFlag' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearFirstRequestFlag() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'SerFlag' field.
      * @return The value.
      */
    public java.lang.Integer getSerFlag() {
      return SerFlag;
    }

    /**
      * Sets the value of the 'SerFlag' field.
      * @param value The value of 'SerFlag'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setSerFlag(int value) {
      validate(fields()[9], value);
      this.SerFlag = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'SerFlag' field has been set.
      * @return True if the 'SerFlag' field has been set, false otherwise.
      */
    public boolean hasSerFlag() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'SerFlag' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearSerFlag() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'HeadFlag' field.
      * @return The value.
      */
    public java.lang.Integer getHeadFlag() {
      return HeadFlag;
    }

    /**
      * Sets the value of the 'HeadFlag' field.
      * @param value The value of 'HeadFlag'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setHeadFlag(int value) {
      validate(fields()[10], value);
      this.HeadFlag = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'HeadFlag' field has been set.
      * @return True if the 'HeadFlag' field has been set, false otherwise.
      */
    public boolean hasHeadFlag() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'HeadFlag' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearHeadFlag() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'Res' field.
      * @return The value.
      */
    public java.lang.Integer getRes() {
      return Res;
    }

    /**
      * Sets the value of the 'Res' field.
      * @param value The value of 'Res'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setRes(int value) {
      validate(fields()[11], value);
      this.Res = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'Res' field has been set.
      * @return True if the 'Res' field has been set, false otherwise.
      */
    public boolean hasRes() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'Res' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearRes() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'Ie' field.
      * @return The value.
      */
    public java.lang.Integer getIe() {
      return Ie;
    }

    /**
      * Sets the value of the 'Ie' field.
      * @param value The value of 'Ie'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setIe(int value) {
      validate(fields()[12], value);
      this.Ie = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'Ie' field has been set.
      * @return True if the 'Ie' field has been set, false otherwise.
      */
    public boolean hasIe() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'Ie' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearIe() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'Portal' field.
      * @return The value.
      */
    public java.lang.Integer getPortal() {
      return Portal;
    }

    /**
      * Sets the value of the 'Portal' field.
      * @param value The value of 'Portal'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setPortal(int value) {
      validate(fields()[13], value);
      this.Portal = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'Portal' field has been set.
      * @return True if the 'Portal' field has been set, false otherwise.
      */
    public boolean hasPortal() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'Portal' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearPortal() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'Resv' field.
      * @return The value.
      */
    public java.lang.Integer getResv() {
      return Resv;
    }

    /**
      * Sets the value of the 'Resv' field.
      * @param value The value of 'Resv'.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder setResv(int value) {
      validate(fields()[14], value);
      this.Resv = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'Resv' field has been set.
      * @return True if the 'Resv' field has been set, false otherwise.
      */
    public boolean hasResv() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'Resv' field.
      * @return This builder.
      */
    public xdrSchema.XdrHttpInfo.Builder clearResv() {
      fieldSetFlags()[14] = false;
      return this;
    }

    @SuppressWarnings("unchecked")
    public XdrHttpInfo build() {
      try {
        XdrHttpInfo record = new XdrHttpInfo();
        record.CtionTime = fieldSetFlags()[0] ? this.CtionTime : (java.lang.Long) defaultValue(fields()[0]);
        record.FirstPacketTime = fieldSetFlags()[1] ? this.FirstPacketTime : (java.lang.Long) defaultValue(fields()[1]);
        record.LastPacketTime = fieldSetFlags()[2] ? this.LastPacketTime : (java.lang.Long) defaultValue(fields()[2]);
        record.ServiceTime = fieldSetFlags()[3] ? this.ServiceTime : (java.lang.Long) defaultValue(fields()[3]);
        record.ContentLenth = fieldSetFlags()[4] ? this.ContentLenth : (java.lang.Long) defaultValue(fields()[4]);
        record.HttpStatus = fieldSetFlags()[5] ? this.HttpStatus : (java.lang.Integer) defaultValue(fields()[5]);
        record.HttpMethod = fieldSetFlags()[6] ? this.HttpMethod : (java.lang.Integer) defaultValue(fields()[6]);
        record.HttpVersion = fieldSetFlags()[7] ? this.HttpVersion : (java.lang.Integer) defaultValue(fields()[7]);
        record.FirstRequestFlag = fieldSetFlags()[8] ? this.FirstRequestFlag : (java.lang.Integer) defaultValue(fields()[8]);
        record.SerFlag = fieldSetFlags()[9] ? this.SerFlag : (java.lang.Integer) defaultValue(fields()[9]);
        record.HeadFlag = fieldSetFlags()[10] ? this.HeadFlag : (java.lang.Integer) defaultValue(fields()[10]);
        record.Res = fieldSetFlags()[11] ? this.Res : (java.lang.Integer) defaultValue(fields()[11]);
        record.Ie = fieldSetFlags()[12] ? this.Ie : (java.lang.Integer) defaultValue(fields()[12]);
        record.Portal = fieldSetFlags()[13] ? this.Portal : (java.lang.Integer) defaultValue(fields()[13]);
        record.Resv = fieldSetFlags()[14] ? this.Resv : (java.lang.Integer) defaultValue(fields()[14]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<XdrHttpInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<XdrHttpInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<XdrHttpInfo>
    READER$ = (org.apache.avro.io.DatumReader<XdrHttpInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
