/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package xdrSchema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class XdrResponseDelay extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6721302488861542412L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"XdrResponseDelay\",\"namespace\":\"xdrSchema\",\"fields\":[{\"name\":\"ResponseDelay\",\"type\":\"long\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<XdrResponseDelay> ENCODER =
      new BinaryMessageEncoder<XdrResponseDelay>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<XdrResponseDelay> DECODER =
      new BinaryMessageDecoder<XdrResponseDelay>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<XdrResponseDelay> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<XdrResponseDelay> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<XdrResponseDelay>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this XdrResponseDelay to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a XdrResponseDelay from a ByteBuffer. */
  public static XdrResponseDelay fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long ResponseDelay;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public XdrResponseDelay() {}

  /**
   * All-args constructor.
   * @param ResponseDelay The new value for ResponseDelay
   */
  public XdrResponseDelay(java.lang.Long ResponseDelay) {
    this.ResponseDelay = ResponseDelay;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ResponseDelay;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ResponseDelay = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ResponseDelay' field.
   * @return The value of the 'ResponseDelay' field.
   */
  public java.lang.Long getResponseDelay() {
    return ResponseDelay;
  }

  /**
   * Sets the value of the 'ResponseDelay' field.
   * @param value the value to set.
   */
  public void setResponseDelay(java.lang.Long value) {
    this.ResponseDelay = value;
  }

  /**
   * Creates a new XdrResponseDelay RecordBuilder.
   * @return A new XdrResponseDelay RecordBuilder
   */
  public static xdrSchema.XdrResponseDelay.Builder newBuilder() {
    return new xdrSchema.XdrResponseDelay.Builder();
  }

  /**
   * Creates a new XdrResponseDelay RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new XdrResponseDelay RecordBuilder
   */
  public static xdrSchema.XdrResponseDelay.Builder newBuilder(xdrSchema.XdrResponseDelay.Builder other) {
    return new xdrSchema.XdrResponseDelay.Builder(other);
  }

  /**
   * Creates a new XdrResponseDelay RecordBuilder by copying an existing XdrResponseDelay instance.
   * @param other The existing instance to copy.
   * @return A new XdrResponseDelay RecordBuilder
   */
  public static xdrSchema.XdrResponseDelay.Builder newBuilder(xdrSchema.XdrResponseDelay other) {
    return new xdrSchema.XdrResponseDelay.Builder(other);
  }

  /**
   * RecordBuilder for XdrResponseDelay instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<XdrResponseDelay>
    implements org.apache.avro.data.RecordBuilder<XdrResponseDelay> {

    private long ResponseDelay;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(xdrSchema.XdrResponseDelay.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ResponseDelay)) {
        this.ResponseDelay = data().deepCopy(fields()[0].schema(), other.ResponseDelay);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing XdrResponseDelay instance
     * @param other The existing instance to copy.
     */
    private Builder(xdrSchema.XdrResponseDelay other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ResponseDelay)) {
        this.ResponseDelay = data().deepCopy(fields()[0].schema(), other.ResponseDelay);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'ResponseDelay' field.
      * @return The value.
      */
    public java.lang.Long getResponseDelay() {
      return ResponseDelay;
    }

    /**
      * Sets the value of the 'ResponseDelay' field.
      * @param value The value of 'ResponseDelay'.
      * @return This builder.
      */
    public xdrSchema.XdrResponseDelay.Builder setResponseDelay(long value) {
      validate(fields()[0], value);
      this.ResponseDelay = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ResponseDelay' field has been set.
      * @return True if the 'ResponseDelay' field has been set, false otherwise.
      */
    public boolean hasResponseDelay() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ResponseDelay' field.
      * @return This builder.
      */
    public xdrSchema.XdrResponseDelay.Builder clearResponseDelay() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @SuppressWarnings("unchecked")
    public XdrResponseDelay build() {
      try {
        XdrResponseDelay record = new XdrResponseDelay();
        record.ResponseDelay = fieldSetFlags()[0] ? this.ResponseDelay : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<XdrResponseDelay>
    WRITER$ = (org.apache.avro.io.DatumWriter<XdrResponseDelay>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<XdrResponseDelay>
    READER$ = (org.apache.avro.io.DatumReader<XdrResponseDelay>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
