/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package xdrSchema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class XdrSsnInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8724640116429503191L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"XdrSsnInfo\",\"namespace\":\"xdrSchema\",\"fields\":[{\"name\":\"UpFlow\",\"type\":\"long\",\"default\":0},{\"name\":\"DownFlow\",\"type\":\"long\",\"default\":0},{\"name\":\"UpPackets\",\"type\":\"long\",\"default\":0},{\"name\":\"DownPackets\",\"type\":\"long\",\"default\":0},{\"name\":\"UpTcpDisorder\",\"type\":\"long\",\"default\":0},{\"name\":\"DownTcpDisorder\",\"type\":\"long\",\"default\":0},{\"name\":\"UpTcpRetransmit\",\"type\":\"long\",\"default\":0},{\"name\":\"DownTcpRetransmit\",\"type\":\"long\",\"default\":0},{\"name\":\"UpFragPackets\",\"type\":\"long\",\"default\":0},{\"name\":\"DownFragPackets\",\"type\":\"long\",\"default\":0},{\"name\":\"UpDuraUpTime\",\"type\":\"int\",\"default\":0},{\"name\":\"DownDuraUpTime\",\"type\":\"int\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<XdrSsnInfo> ENCODER =
      new BinaryMessageEncoder<XdrSsnInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<XdrSsnInfo> DECODER =
      new BinaryMessageDecoder<XdrSsnInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<XdrSsnInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<XdrSsnInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<XdrSsnInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this XdrSsnInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a XdrSsnInfo from a ByteBuffer. */
  public static XdrSsnInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long UpFlow;
  @Deprecated public long DownFlow;
  @Deprecated public long UpPackets;
  @Deprecated public long DownPackets;
  @Deprecated public long UpTcpDisorder;
  @Deprecated public long DownTcpDisorder;
  @Deprecated public long UpTcpRetransmit;
  @Deprecated public long DownTcpRetransmit;
  @Deprecated public long UpFragPackets;
  @Deprecated public long DownFragPackets;
  @Deprecated public int UpDuraUpTime;
  @Deprecated public int DownDuraUpTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public XdrSsnInfo() {}

  /**
   * All-args constructor.
   * @param UpFlow The new value for UpFlow
   * @param DownFlow The new value for DownFlow
   * @param UpPackets The new value for UpPackets
   * @param DownPackets The new value for DownPackets
   * @param UpTcpDisorder The new value for UpTcpDisorder
   * @param DownTcpDisorder The new value for DownTcpDisorder
   * @param UpTcpRetransmit The new value for UpTcpRetransmit
   * @param DownTcpRetransmit The new value for DownTcpRetransmit
   * @param UpFragPackets The new value for UpFragPackets
   * @param DownFragPackets The new value for DownFragPackets
   * @param UpDuraUpTime The new value for UpDuraUpTime
   * @param DownDuraUpTime The new value for DownDuraUpTime
   */
  public XdrSsnInfo(java.lang.Long UpFlow, java.lang.Long DownFlow, java.lang.Long UpPackets, java.lang.Long DownPackets, java.lang.Long UpTcpDisorder, java.lang.Long DownTcpDisorder, java.lang.Long UpTcpRetransmit, java.lang.Long DownTcpRetransmit, java.lang.Long UpFragPackets, java.lang.Long DownFragPackets, java.lang.Integer UpDuraUpTime, java.lang.Integer DownDuraUpTime) {
    this.UpFlow = UpFlow;
    this.DownFlow = DownFlow;
    this.UpPackets = UpPackets;
    this.DownPackets = DownPackets;
    this.UpTcpDisorder = UpTcpDisorder;
    this.DownTcpDisorder = DownTcpDisorder;
    this.UpTcpRetransmit = UpTcpRetransmit;
    this.DownTcpRetransmit = DownTcpRetransmit;
    this.UpFragPackets = UpFragPackets;
    this.DownFragPackets = DownFragPackets;
    this.UpDuraUpTime = UpDuraUpTime;
    this.DownDuraUpTime = DownDuraUpTime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return UpFlow;
    case 1: return DownFlow;
    case 2: return UpPackets;
    case 3: return DownPackets;
    case 4: return UpTcpDisorder;
    case 5: return DownTcpDisorder;
    case 6: return UpTcpRetransmit;
    case 7: return DownTcpRetransmit;
    case 8: return UpFragPackets;
    case 9: return DownFragPackets;
    case 10: return UpDuraUpTime;
    case 11: return DownDuraUpTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: UpFlow = (java.lang.Long)value$; break;
    case 1: DownFlow = (java.lang.Long)value$; break;
    case 2: UpPackets = (java.lang.Long)value$; break;
    case 3: DownPackets = (java.lang.Long)value$; break;
    case 4: UpTcpDisorder = (java.lang.Long)value$; break;
    case 5: DownTcpDisorder = (java.lang.Long)value$; break;
    case 6: UpTcpRetransmit = (java.lang.Long)value$; break;
    case 7: DownTcpRetransmit = (java.lang.Long)value$; break;
    case 8: UpFragPackets = (java.lang.Long)value$; break;
    case 9: DownFragPackets = (java.lang.Long)value$; break;
    case 10: UpDuraUpTime = (java.lang.Integer)value$; break;
    case 11: DownDuraUpTime = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'UpFlow' field.
   * @return The value of the 'UpFlow' field.
   */
  public java.lang.Long getUpFlow() {
    return UpFlow;
  }

  /**
   * Sets the value of the 'UpFlow' field.
   * @param value the value to set.
   */
  public void setUpFlow(java.lang.Long value) {
    this.UpFlow = value;
  }

  /**
   * Gets the value of the 'DownFlow' field.
   * @return The value of the 'DownFlow' field.
   */
  public java.lang.Long getDownFlow() {
    return DownFlow;
  }

  /**
   * Sets the value of the 'DownFlow' field.
   * @param value the value to set.
   */
  public void setDownFlow(java.lang.Long value) {
    this.DownFlow = value;
  }

  /**
   * Gets the value of the 'UpPackets' field.
   * @return The value of the 'UpPackets' field.
   */
  public java.lang.Long getUpPackets() {
    return UpPackets;
  }

  /**
   * Sets the value of the 'UpPackets' field.
   * @param value the value to set.
   */
  public void setUpPackets(java.lang.Long value) {
    this.UpPackets = value;
  }

  /**
   * Gets the value of the 'DownPackets' field.
   * @return The value of the 'DownPackets' field.
   */
  public java.lang.Long getDownPackets() {
    return DownPackets;
  }

  /**
   * Sets the value of the 'DownPackets' field.
   * @param value the value to set.
   */
  public void setDownPackets(java.lang.Long value) {
    this.DownPackets = value;
  }

  /**
   * Gets the value of the 'UpTcpDisorder' field.
   * @return The value of the 'UpTcpDisorder' field.
   */
  public java.lang.Long getUpTcpDisorder() {
    return UpTcpDisorder;
  }

  /**
   * Sets the value of the 'UpTcpDisorder' field.
   * @param value the value to set.
   */
  public void setUpTcpDisorder(java.lang.Long value) {
    this.UpTcpDisorder = value;
  }

  /**
   * Gets the value of the 'DownTcpDisorder' field.
   * @return The value of the 'DownTcpDisorder' field.
   */
  public java.lang.Long getDownTcpDisorder() {
    return DownTcpDisorder;
  }

  /**
   * Sets the value of the 'DownTcpDisorder' field.
   * @param value the value to set.
   */
  public void setDownTcpDisorder(java.lang.Long value) {
    this.DownTcpDisorder = value;
  }

  /**
   * Gets the value of the 'UpTcpRetransmit' field.
   * @return The value of the 'UpTcpRetransmit' field.
   */
  public java.lang.Long getUpTcpRetransmit() {
    return UpTcpRetransmit;
  }

  /**
   * Sets the value of the 'UpTcpRetransmit' field.
   * @param value the value to set.
   */
  public void setUpTcpRetransmit(java.lang.Long value) {
    this.UpTcpRetransmit = value;
  }

  /**
   * Gets the value of the 'DownTcpRetransmit' field.
   * @return The value of the 'DownTcpRetransmit' field.
   */
  public java.lang.Long getDownTcpRetransmit() {
    return DownTcpRetransmit;
  }

  /**
   * Sets the value of the 'DownTcpRetransmit' field.
   * @param value the value to set.
   */
  public void setDownTcpRetransmit(java.lang.Long value) {
    this.DownTcpRetransmit = value;
  }

  /**
   * Gets the value of the 'UpFragPackets' field.
   * @return The value of the 'UpFragPackets' field.
   */
  public java.lang.Long getUpFragPackets() {
    return UpFragPackets;
  }

  /**
   * Sets the value of the 'UpFragPackets' field.
   * @param value the value to set.
   */
  public void setUpFragPackets(java.lang.Long value) {
    this.UpFragPackets = value;
  }

  /**
   * Gets the value of the 'DownFragPackets' field.
   * @return The value of the 'DownFragPackets' field.
   */
  public java.lang.Long getDownFragPackets() {
    return DownFragPackets;
  }

  /**
   * Sets the value of the 'DownFragPackets' field.
   * @param value the value to set.
   */
  public void setDownFragPackets(java.lang.Long value) {
    this.DownFragPackets = value;
  }

  /**
   * Gets the value of the 'UpDuraUpTime' field.
   * @return The value of the 'UpDuraUpTime' field.
   */
  public java.lang.Integer getUpDuraUpTime() {
    return UpDuraUpTime;
  }

  /**
   * Sets the value of the 'UpDuraUpTime' field.
   * @param value the value to set.
   */
  public void setUpDuraUpTime(java.lang.Integer value) {
    this.UpDuraUpTime = value;
  }

  /**
   * Gets the value of the 'DownDuraUpTime' field.
   * @return The value of the 'DownDuraUpTime' field.
   */
  public java.lang.Integer getDownDuraUpTime() {
    return DownDuraUpTime;
  }

  /**
   * Sets the value of the 'DownDuraUpTime' field.
   * @param value the value to set.
   */
  public void setDownDuraUpTime(java.lang.Integer value) {
    this.DownDuraUpTime = value;
  }

  /**
   * Creates a new XdrSsnInfo RecordBuilder.
   * @return A new XdrSsnInfo RecordBuilder
   */
  public static xdrSchema.XdrSsnInfo.Builder newBuilder() {
    return new xdrSchema.XdrSsnInfo.Builder();
  }

  /**
   * Creates a new XdrSsnInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new XdrSsnInfo RecordBuilder
   */
  public static xdrSchema.XdrSsnInfo.Builder newBuilder(xdrSchema.XdrSsnInfo.Builder other) {
    return new xdrSchema.XdrSsnInfo.Builder(other);
  }

  /**
   * Creates a new XdrSsnInfo RecordBuilder by copying an existing XdrSsnInfo instance.
   * @param other The existing instance to copy.
   * @return A new XdrSsnInfo RecordBuilder
   */
  public static xdrSchema.XdrSsnInfo.Builder newBuilder(xdrSchema.XdrSsnInfo other) {
    return new xdrSchema.XdrSsnInfo.Builder(other);
  }

  /**
   * RecordBuilder for XdrSsnInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<XdrSsnInfo>
    implements org.apache.avro.data.RecordBuilder<XdrSsnInfo> {

    private long UpFlow;
    private long DownFlow;
    private long UpPackets;
    private long DownPackets;
    private long UpTcpDisorder;
    private long DownTcpDisorder;
    private long UpTcpRetransmit;
    private long DownTcpRetransmit;
    private long UpFragPackets;
    private long DownFragPackets;
    private int UpDuraUpTime;
    private int DownDuraUpTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(xdrSchema.XdrSsnInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.UpFlow)) {
        this.UpFlow = data().deepCopy(fields()[0].schema(), other.UpFlow);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.DownFlow)) {
        this.DownFlow = data().deepCopy(fields()[1].schema(), other.DownFlow);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UpPackets)) {
        this.UpPackets = data().deepCopy(fields()[2].schema(), other.UpPackets);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DownPackets)) {
        this.DownPackets = data().deepCopy(fields()[3].schema(), other.DownPackets);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.UpTcpDisorder)) {
        this.UpTcpDisorder = data().deepCopy(fields()[4].schema(), other.UpTcpDisorder);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.DownTcpDisorder)) {
        this.DownTcpDisorder = data().deepCopy(fields()[5].schema(), other.DownTcpDisorder);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.UpTcpRetransmit)) {
        this.UpTcpRetransmit = data().deepCopy(fields()[6].schema(), other.UpTcpRetransmit);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.DownTcpRetransmit)) {
        this.DownTcpRetransmit = data().deepCopy(fields()[7].schema(), other.DownTcpRetransmit);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.UpFragPackets)) {
        this.UpFragPackets = data().deepCopy(fields()[8].schema(), other.UpFragPackets);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.DownFragPackets)) {
        this.DownFragPackets = data().deepCopy(fields()[9].schema(), other.DownFragPackets);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.UpDuraUpTime)) {
        this.UpDuraUpTime = data().deepCopy(fields()[10].schema(), other.UpDuraUpTime);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.DownDuraUpTime)) {
        this.DownDuraUpTime = data().deepCopy(fields()[11].schema(), other.DownDuraUpTime);
        fieldSetFlags()[11] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing XdrSsnInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(xdrSchema.XdrSsnInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.UpFlow)) {
        this.UpFlow = data().deepCopy(fields()[0].schema(), other.UpFlow);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.DownFlow)) {
        this.DownFlow = data().deepCopy(fields()[1].schema(), other.DownFlow);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UpPackets)) {
        this.UpPackets = data().deepCopy(fields()[2].schema(), other.UpPackets);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DownPackets)) {
        this.DownPackets = data().deepCopy(fields()[3].schema(), other.DownPackets);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.UpTcpDisorder)) {
        this.UpTcpDisorder = data().deepCopy(fields()[4].schema(), other.UpTcpDisorder);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.DownTcpDisorder)) {
        this.DownTcpDisorder = data().deepCopy(fields()[5].schema(), other.DownTcpDisorder);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.UpTcpRetransmit)) {
        this.UpTcpRetransmit = data().deepCopy(fields()[6].schema(), other.UpTcpRetransmit);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.DownTcpRetransmit)) {
        this.DownTcpRetransmit = data().deepCopy(fields()[7].schema(), other.DownTcpRetransmit);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.UpFragPackets)) {
        this.UpFragPackets = data().deepCopy(fields()[8].schema(), other.UpFragPackets);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.DownFragPackets)) {
        this.DownFragPackets = data().deepCopy(fields()[9].schema(), other.DownFragPackets);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.UpDuraUpTime)) {
        this.UpDuraUpTime = data().deepCopy(fields()[10].schema(), other.UpDuraUpTime);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.DownDuraUpTime)) {
        this.DownDuraUpTime = data().deepCopy(fields()[11].schema(), other.DownDuraUpTime);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'UpFlow' field.
      * @return The value.
      */
    public java.lang.Long getUpFlow() {
      return UpFlow;
    }

    /**
      * Sets the value of the 'UpFlow' field.
      * @param value The value of 'UpFlow'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setUpFlow(long value) {
      validate(fields()[0], value);
      this.UpFlow = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'UpFlow' field has been set.
      * @return True if the 'UpFlow' field has been set, false otherwise.
      */
    public boolean hasUpFlow() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'UpFlow' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearUpFlow() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'DownFlow' field.
      * @return The value.
      */
    public java.lang.Long getDownFlow() {
      return DownFlow;
    }

    /**
      * Sets the value of the 'DownFlow' field.
      * @param value The value of 'DownFlow'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setDownFlow(long value) {
      validate(fields()[1], value);
      this.DownFlow = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'DownFlow' field has been set.
      * @return True if the 'DownFlow' field has been set, false otherwise.
      */
    public boolean hasDownFlow() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'DownFlow' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearDownFlow() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'UpPackets' field.
      * @return The value.
      */
    public java.lang.Long getUpPackets() {
      return UpPackets;
    }

    /**
      * Sets the value of the 'UpPackets' field.
      * @param value The value of 'UpPackets'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setUpPackets(long value) {
      validate(fields()[2], value);
      this.UpPackets = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'UpPackets' field has been set.
      * @return True if the 'UpPackets' field has been set, false otherwise.
      */
    public boolean hasUpPackets() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'UpPackets' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearUpPackets() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'DownPackets' field.
      * @return The value.
      */
    public java.lang.Long getDownPackets() {
      return DownPackets;
    }

    /**
      * Sets the value of the 'DownPackets' field.
      * @param value The value of 'DownPackets'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setDownPackets(long value) {
      validate(fields()[3], value);
      this.DownPackets = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'DownPackets' field has been set.
      * @return True if the 'DownPackets' field has been set, false otherwise.
      */
    public boolean hasDownPackets() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'DownPackets' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearDownPackets() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'UpTcpDisorder' field.
      * @return The value.
      */
    public java.lang.Long getUpTcpDisorder() {
      return UpTcpDisorder;
    }

    /**
      * Sets the value of the 'UpTcpDisorder' field.
      * @param value The value of 'UpTcpDisorder'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setUpTcpDisorder(long value) {
      validate(fields()[4], value);
      this.UpTcpDisorder = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'UpTcpDisorder' field has been set.
      * @return True if the 'UpTcpDisorder' field has been set, false otherwise.
      */
    public boolean hasUpTcpDisorder() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'UpTcpDisorder' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearUpTcpDisorder() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'DownTcpDisorder' field.
      * @return The value.
      */
    public java.lang.Long getDownTcpDisorder() {
      return DownTcpDisorder;
    }

    /**
      * Sets the value of the 'DownTcpDisorder' field.
      * @param value The value of 'DownTcpDisorder'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setDownTcpDisorder(long value) {
      validate(fields()[5], value);
      this.DownTcpDisorder = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'DownTcpDisorder' field has been set.
      * @return True if the 'DownTcpDisorder' field has been set, false otherwise.
      */
    public boolean hasDownTcpDisorder() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'DownTcpDisorder' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearDownTcpDisorder() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'UpTcpRetransmit' field.
      * @return The value.
      */
    public java.lang.Long getUpTcpRetransmit() {
      return UpTcpRetransmit;
    }

    /**
      * Sets the value of the 'UpTcpRetransmit' field.
      * @param value The value of 'UpTcpRetransmit'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setUpTcpRetransmit(long value) {
      validate(fields()[6], value);
      this.UpTcpRetransmit = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'UpTcpRetransmit' field has been set.
      * @return True if the 'UpTcpRetransmit' field has been set, false otherwise.
      */
    public boolean hasUpTcpRetransmit() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'UpTcpRetransmit' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearUpTcpRetransmit() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'DownTcpRetransmit' field.
      * @return The value.
      */
    public java.lang.Long getDownTcpRetransmit() {
      return DownTcpRetransmit;
    }

    /**
      * Sets the value of the 'DownTcpRetransmit' field.
      * @param value The value of 'DownTcpRetransmit'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setDownTcpRetransmit(long value) {
      validate(fields()[7], value);
      this.DownTcpRetransmit = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'DownTcpRetransmit' field has been set.
      * @return True if the 'DownTcpRetransmit' field has been set, false otherwise.
      */
    public boolean hasDownTcpRetransmit() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'DownTcpRetransmit' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearDownTcpRetransmit() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'UpFragPackets' field.
      * @return The value.
      */
    public java.lang.Long getUpFragPackets() {
      return UpFragPackets;
    }

    /**
      * Sets the value of the 'UpFragPackets' field.
      * @param value The value of 'UpFragPackets'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setUpFragPackets(long value) {
      validate(fields()[8], value);
      this.UpFragPackets = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'UpFragPackets' field has been set.
      * @return True if the 'UpFragPackets' field has been set, false otherwise.
      */
    public boolean hasUpFragPackets() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'UpFragPackets' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearUpFragPackets() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'DownFragPackets' field.
      * @return The value.
      */
    public java.lang.Long getDownFragPackets() {
      return DownFragPackets;
    }

    /**
      * Sets the value of the 'DownFragPackets' field.
      * @param value The value of 'DownFragPackets'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setDownFragPackets(long value) {
      validate(fields()[9], value);
      this.DownFragPackets = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'DownFragPackets' field has been set.
      * @return True if the 'DownFragPackets' field has been set, false otherwise.
      */
    public boolean hasDownFragPackets() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'DownFragPackets' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearDownFragPackets() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'UpDuraUpTime' field.
      * @return The value.
      */
    public java.lang.Integer getUpDuraUpTime() {
      return UpDuraUpTime;
    }

    /**
      * Sets the value of the 'UpDuraUpTime' field.
      * @param value The value of 'UpDuraUpTime'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setUpDuraUpTime(int value) {
      validate(fields()[10], value);
      this.UpDuraUpTime = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'UpDuraUpTime' field has been set.
      * @return True if the 'UpDuraUpTime' field has been set, false otherwise.
      */
    public boolean hasUpDuraUpTime() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'UpDuraUpTime' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearUpDuraUpTime() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'DownDuraUpTime' field.
      * @return The value.
      */
    public java.lang.Integer getDownDuraUpTime() {
      return DownDuraUpTime;
    }

    /**
      * Sets the value of the 'DownDuraUpTime' field.
      * @param value The value of 'DownDuraUpTime'.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder setDownDuraUpTime(int value) {
      validate(fields()[11], value);
      this.DownDuraUpTime = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'DownDuraUpTime' field has been set.
      * @return True if the 'DownDuraUpTime' field has been set, false otherwise.
      */
    public boolean hasDownDuraUpTime() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'DownDuraUpTime' field.
      * @return This builder.
      */
    public xdrSchema.XdrSsnInfo.Builder clearDownDuraUpTime() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @SuppressWarnings("unchecked")
    public XdrSsnInfo build() {
      try {
        XdrSsnInfo record = new XdrSsnInfo();
        record.UpFlow = fieldSetFlags()[0] ? this.UpFlow : (java.lang.Long) defaultValue(fields()[0]);
        record.DownFlow = fieldSetFlags()[1] ? this.DownFlow : (java.lang.Long) defaultValue(fields()[1]);
        record.UpPackets = fieldSetFlags()[2] ? this.UpPackets : (java.lang.Long) defaultValue(fields()[2]);
        record.DownPackets = fieldSetFlags()[3] ? this.DownPackets : (java.lang.Long) defaultValue(fields()[3]);
        record.UpTcpDisorder = fieldSetFlags()[4] ? this.UpTcpDisorder : (java.lang.Long) defaultValue(fields()[4]);
        record.DownTcpDisorder = fieldSetFlags()[5] ? this.DownTcpDisorder : (java.lang.Long) defaultValue(fields()[5]);
        record.UpTcpRetransmit = fieldSetFlags()[6] ? this.UpTcpRetransmit : (java.lang.Long) defaultValue(fields()[6]);
        record.DownTcpRetransmit = fieldSetFlags()[7] ? this.DownTcpRetransmit : (java.lang.Long) defaultValue(fields()[7]);
        record.UpFragPackets = fieldSetFlags()[8] ? this.UpFragPackets : (java.lang.Long) defaultValue(fields()[8]);
        record.DownFragPackets = fieldSetFlags()[9] ? this.DownFragPackets : (java.lang.Long) defaultValue(fields()[9]);
        record.UpDuraUpTime = fieldSetFlags()[10] ? this.UpDuraUpTime : (java.lang.Integer) defaultValue(fields()[10]);
        record.DownDuraUpTime = fieldSetFlags()[11] ? this.DownDuraUpTime : (java.lang.Integer) defaultValue(fields()[11]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<XdrSsnInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<XdrSsnInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<XdrSsnInfo>
    READER$ = (org.apache.avro.io.DatumReader<XdrSsnInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
